# Generated by Django 3.0.7 on 2020-07-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='secuences/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Geolocalizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Secuence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('bio_id', models.TextField()),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('upload_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
