# Generated by Django 3.0.7 on 2020-07-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpFinalBioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuence',
            name='source',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
