# Generated by Django 3.0.7 on 2020-07-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpFinalBioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='secuences/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Secuencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=500)),
                ('latitud', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='secuences/files/')),
            ],
        ),
    ]
