# Generated by Django 3.0.7 on 2020-07-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpFinalBioApp', '0002_fastafile_secuencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secuence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=500)),
                ('bio_id', models.TextField()),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Secuencia',
        ),
    ]
