# Generated by Django 3.0.7 on 2020-07-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpFinalBioApp', '0002_secuence_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuence',
            name='date',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
