# Generated by Django 3.0.7 on 2020-07-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TpFinalBioApp', '0003_auto_20200703_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secuence',
            old_name='adress',
            new_name='address',
        ),
    ]
